name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          body: |
            version ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: success()
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        if: success()
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: siriuszg/kong-ingress-controller:${{ env.RELEASE_VERSION }},siriuszg/kong-ingress-controller:latest
